version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      MYSQL_USER: zluqet_user
      MYSQL_PASSWORD: securepassword
      MYSQL_HOST: db
      MYSQL_DATABASE: zluqetdb
      DATABASE_URL: mysql+pymysql://zluqet_user:securepassword@db/zluqetdb

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: zluqetdb
      MYSQL_USER: zluqet_user
      MYSQL_PASSWORD: securepassword
      MYSQL_ROOT_PASSWORD: securepassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: